app = "tradingia"
primary_region = "mad"

[http_service]
internal_port = 8080  # Match the Dockerfile
force_https = true
auto_start_machines = true
auto_stop_machines = true
min_machines_running = 0
processes = ["app"]

[env]
# Add any required environment variables here

[vm]
cpu_kind = "shared"
cpus = 1
memory = "2gb"